# Generated by Django 6.0.1 on 2026-02-03 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoBoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ho', models.CharField(max_length=200, verbose_name='TÃªn há»“ bÆ¡i')),
                ('dia_chi', models.TextField(verbose_name='Ä\x90á»‹a chá»‰')),
                ('do_sau', models.FloatField(help_text='Ä\x90á»™ sÃ¢u tÃ\xadnh báº±ng mÃ©t', verbose_name='Ä\x90á»™ sÃ¢u (m)')),
                ('suc_chua', models.IntegerField(verbose_name='Sá»©c chá»©a tá»‘i Ä‘a')),
                ('gia_ve_nguoi_lon', models.DecimalField(decimal_places=0, default=50000, max_digits=10)),
                ('gia_ve_tre_em', models.DecimalField(decimal_places=0, default=30000, max_digits=10)),
                ('trang_thai', models.CharField(choices=[('MO', 'Ä\x90ang má»Ÿ'), ('BAO_TRI', 'Báº£o trÃ¬'), ('DONG', 'Ä\x90Ã³ng cá»\xada')], default='MO', max_length=20)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='ho_boi/')),
            ],
        ),
        migrations.CreateModel(
            name='DatVe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('ngay_su_dung', models.DateField(verbose_name='NgÃ\xa0y bÆ¡i')),
                ('so_luong_nguoi_lon', models.IntegerField(default=1)),
                ('so_luong_tre_em', models.IntegerField(default=0)),
                ('tong_tien', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='KhÃ¡ch hÃ\xa0ng')),
                ('ho_boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_ho_boi.hoboi', verbose_name='Há»“ bÆ¡i')),
            ],
        ),
    ]
