# Generated by Django 6.0.2 on 2026-02-05 18:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datve',
            options={'verbose_name': 'Vé đặt', 'verbose_name_plural': 'Danh sách Vé đặt'},
        ),
        migrations.AlterModelOptions(
            name='hoboi',
            options={'verbose_name': 'Hồ bơi', 'verbose_name_plural': 'Danh sách Hồ bơi'},
        ),
        migrations.AddField(
            model_name='hoboi',
            name='kinh_do',
            field=models.FloatField(default=10.107, verbose_name='Kinh độ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoboi',
            name='vi_do',
            field=models.FloatField(default=106.7, verbose_name='Vĩ độ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datve',
            name='ho_boi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_ho_boi.hoboi', verbose_name='Hồ bơi'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='ngay_dat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='ngay_su_dung',
            field=models.DateField(verbose_name='Ngày bơi'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='so_luong_nguoi_lon',
            field=models.IntegerField(default=1, verbose_name='Số người lớn'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='so_luong_tre_em',
            field=models.IntegerField(default=0, verbose_name='Số trẻ em'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='dia_chi',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='do_sau',
            field=models.FloatField(help_text='Độ sâu tính bằng mét', verbose_name='Độ sâu (m)'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='gia_ve_nguoi_lon',
            field=models.DecimalField(decimal_places=0, default=Decimal('50000'), max_digits=10, verbose_name='Giá vé người lớn'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='gia_ve_tre_em',
            field=models.DecimalField(decimal_places=0, default=Decimal('30000'), max_digits=10, verbose_name='Giá vé trẻ em'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='ho_boi/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='suc_chua',
            field=models.IntegerField(verbose_name='Sức chứa tối đa'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='ten_ho',
            field=models.CharField(max_length=200, verbose_name='Tên hồ bơi'),
        ),
        migrations.AlterField(
            model_name='hoboi',
            name='trang_thai',
            field=models.CharField(choices=[('MO', 'Đang mở'), ('BAO_TRI', 'Bảo trì'), ('DONG', 'Đóng cửa')], default='MO', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
