# Generated by Django 6.0.1 on 2026-03-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0002_alter_datve_options_alter_hoboi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(choices=[('Tiền mặt', 'Tiền mặt'), ('Thẻ ngân hàng', 'Thẻ ngân hàng'), ('Thanh toán di động', 'Thanh toán di động')], default='Tiền mặt', max_length=50, verbose_name='Phương thức')),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('trang_thai', models.CharField(choices=[('Hoàn thành', 'Hoàn thành'), ('Đang chờ', 'Đang chờ'), ('Hủy', 'Hủy')], default='Hoàn thành', max_length=20, verbose_name='Trạng thái')),
                ('dat_ve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_ho_boi.datve', verbose_name='Vé đặt')),
            ],
            options={
                'verbose_name': 'Lịch sử thanh toán',
                'verbose_name_plural': 'Lịch sử thanh toán',
            },
        ),
    ]
