# Generated by Django 6.0.2 on 2026-04-15 02:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0003_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hồ bơi')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Link ảnh minh họa')),
                ('price_adult', models.IntegerField(default=0, verbose_name='Giá vé người lớn')),
                ('status_code', models.CharField(choices=[('MO', 'Đang mở cửa'), ('DONG', 'Đóng cửa')], default='MO', max_length=10)),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm số (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quan_ly_ho_boi.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
    ]
