# Generated by Django 6.0.4 on 2026-04-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0004_pool_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pool',
        ),
        migrations.AddField(
            model_name='review',
            name='ho_boi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quan_ly_ho_boi.hoboi'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
    ]
