# Generated by Django 6.0.4 on 2026-04-17 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0005_remove_review_pool_review_ho_boi_delete_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='datve',
            name='gio_su_dung',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Giờ bơi'),
        ),
        migrations.AddField(
            model_name='hoboi',
            name='gio_dong_cua',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Giờ đóng cửa'),
        ),
        migrations.AddField(
            model_name='hoboi',
            name='gio_mo_cua',
            field=models.TimeField(default=datetime.time(6, 0), verbose_name='Giờ mở cửa'),
        ),
    ]
