# Generated by Django 6.0.4 on 2026-05-02 09:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0006_datve_gio_su_dung_hoboi_gio_dong_cua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungCuBoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dung_cu', models.CharField(max_length=200, verbose_name='Tên dụng cụ')),
                ('loai_dung_cu', models.CharField(choices=[('PHAO', 'Phao bơi'), ('KINH', 'Kính bơi'), ('MU', 'Mũ bơi'), ('QUAN_AO', 'Quần áo bơi'), ('KHAC', 'Khác')], default='PHAO', max_length=20, verbose_name='Loại dụng cụ')),
                ('gia_thue', models.DecimalField(decimal_places=0, default=Decimal('10000'), max_digits=10, verbose_name='Giá thuê/lần')),
                ('so_luong_con_lai', models.IntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='dung_cu/', verbose_name='Hình ảnh')),
                ('ho_boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dung_cu', to='quan_ly_ho_boi.hoboi', verbose_name='Hồ bơi')),
            ],
            options={
                'verbose_name': 'Dụng cụ bơi',
                'verbose_name_plural': 'Danh sách Dụng cụ bơi',
            },
        ),
    ]
