# Generated by Django 6.0.4 on 2026-05-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0007_dungcuboi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('hinh_thuc', models.CharField(choices=[('THUE', 'Cho thuê'), ('BAN', 'Bán đứt')], max_length=10, verbose_name='Hình thức')),
                ('so_luong_kho', models.IntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('don_gia_thuc_te', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Đơn giá thực tế')),
                ('trang_thai', models.CharField(blank=True, choices=[('DANG_MUON', 'Đang mượn'), ('DA_TRA', 'Đã trả'), ('HONG_MAT', 'Hỏng/Mất'), ('KHONG_AP_DUNG', 'Không áp dụng')], max_length=20, verbose_name='Trạng thái')),
                ('dat_ve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_ho_boi.datve', verbose_name='Vé đặt')),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_ho_boi.dichvu', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Chi tiết dịch vụ',
                'verbose_name_plural': 'Chi tiết dịch vụ',
            },
        ),
        migrations.DeleteModel(
            name='DungCuBoi',
        ),
    ]
