# Generated by Django 6.0.1 on 2026-05-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0008_dichvu_chitietdichvu_delete_dungcuboi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhHoBoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='ho_boi_gallery/', verbose_name='Hình ảnh')),
                ('ho_boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_hinh_anh', to='quan_ly_ho_boi.hoboi', verbose_name='Hồ bơi')),
            ],
            options={
                'verbose_name': 'Hình ảnh hồ bơi',
                'verbose_name_plural': 'Bộ sưu tập ảnh hồ bơi',
            },
        ),
    ]
