# Generated by Django 6.0.1 on 2026-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_ho_boi', '0009_hinhanhhoboi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvu',
            name='don_vi_tinh',
            field=models.CharField(default='món', max_length=50, verbose_name='Đơn vị tính'),
        ),
    ]
